# Generated by Django 4.2.24 on 2025-09-26 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dmsanpham',
            fields=[
                ('madm', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tendm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='khachhang',
            fields=[
                ('makh', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenkh', models.CharField(max_length=50)),
                ('diachi', models.CharField(max_length=50)),
                ('sdt', models.CharField(max_length=10)),
                ('capdotv', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='khuyenmai',
            fields=[
                ('makm', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenkm', models.CharField(max_length=50)),
                ('ngaybd', models.DateField()),
                ('ngaykt', models.DateField()),
                ('giamgia', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='loaithetv',
            fields=[
                ('maloaithe', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenthe', models.CharField(max_length=30)),
                ('uudai', models.FloatField()),
                ('dieukien', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='nhacc',
            fields=[
                ('mancc', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tencc', models.CharField(max_length=50)),
                ('diachi', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nhanvien',
            fields=[
                ('manv', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tennv', models.CharField(max_length=50)),
                ('diachi', models.CharField(max_length=50)),
                ('gioitinh', models.CharField(max_length=5)),
                ('cccd', models.CharField(max_length=20)),
                ('sdt', models.CharField(max_length=10)),
                ('ngaysinh', models.DateField()),
                ('chucvu', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tknhanvien',
            fields=[
                ('tentk', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('matkhau', models.CharField(max_length=20)),
                ('chucvu', models.CharField(max_length=30)),
                ('manv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fresh_Products.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='tkkhachhang',
            fields=[
                ('tentk', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('matkhau', models.CharField(max_length=20)),
                ('makh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fresh_Products.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='sanpham',
            fields=[
                ('masp', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tensp', models.CharField(max_length=50)),
                ('donvitinh', models.CharField(max_length=20)),
                ('gia1dv', models.IntegerField()),
                ('soluongtk', models.IntegerField()),
                ('xuatxu', models.CharField(max_length=30)),
                ('madm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fresh_Products.dmsanpham')),
                ('mancc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fresh_Products.nhacc')),
            ],
        ),
        migrations.CreateModel(
            name='hoadon',
            fields=[
                ('mahd', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ngaydat', models.DateField()),
                ('trangthaihd', models.CharField(max_length=30)),
                ('phuongthucgh', models.CharField(max_length=30)),
                ('ngaygiao', models.DateField()),
                ('tongtien', models.IntegerField()),
                ('makh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fresh_Products.khachhang')),
                ('makm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fresh_Products.khuyenmai')),
                ('manv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fresh_Products.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='hinhanhsp',
            fields=[
                ('mahinh', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenhinh', models.CharField(max_length=50)),
                ('masp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fresh_Products.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='chitiethoadon',
            fields=[
                ('macthd', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('soluongban', models.FloatField()),
                ('giaban', models.IntegerField()),
                ('mahd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fresh_Products.hoadon')),
                ('masp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fresh_Products.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='capnhatthe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaycap', models.DateField()),
                ('makh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fresh_Products.khachhang')),
                ('maloaithe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fresh_Products.loaithetv')),
            ],
        ),
    ]
