# Generated by Django 4.2.24 on 2025-09-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fresh_Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capnhatthe',
            unique_together={('makh', 'maloaithe')},
        ),
    ]
