# Generated by Django 4.2.24 on 2025-10-01 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fresh_Products', '0002_alter_capnhatthe_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='makm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Fresh_Products.khuyenmai'),
        ),
    ]
