# Generated by Django 4.2.24 on 2025-10-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fresh_Products', '0003_sanpham_makm'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='phuongthucthtoan',
            field=models.CharField(choices=[('Cash', 'Tiền mặt'), ('Bank', 'Chuyển khoản')], default='Cash', max_length=20),
            preserve_default=False,
        ),
    ]
