# Generated by Django 4.2.24 on 2025-10-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fresh_Products', '0004_hoadon_phuongthucthtoan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='phuongthucthtoan',
            field=models.CharField(choices=[('Cash', 'Tiền mặt'), ('Bank', 'Chuyển khoản')], default='Cash', max_length=20),
        ),
    ]
