# Generated by Django 4.2.24 on 2025-10-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fresh_Products', '0005_alter_hoadon_phuongthucthtoan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='makh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Fresh_Products.khachhang'),
        ),
    ]
